post_install() {
    mv /usr/share/grub/background.png /usr/share/grub/background.png.save
    cp /usr/share/backgrounds/openbox-wall-blue.png /usr/share/grub/background.png
}

post_upgrade() {
    rm -f /usr/share/grub/background.png
    mv /usr/share/grub/background.png.save /usr/share/grub/background.png
}

post_remove() {
    rm -f /usr/share/grub/background.png
    mv /usr/share/grub/background.png.save /usr/share/grub/background.png
}