
post_install(){

if [ -e "/usr/share/gnome-shell/extensions/manjaro-update@Chrysostomus/schemas/gschemas.compiled" ]; then
	rm -f /usr/share/gnome-shell/extensions/manjaro-update@Chrysostomus/schemas/gschemas.compiled
fi
	glib-compile-schemas /usr/share/gnome-shell/extensions/manjaro-update@Chrysostomus/schemas/

}

post_upgrade(){
	
	post_install
	
}

post_remove() {

rm -R /usr/share/gnome-shell/extensions/manjaro-update@Chrysostomus

}
